# Time Config
TIME:
  DATE: '06/24/24 17:00:00' # Format is "MM/dd/yy HH:mm:ss" hour format in 24h clock.
  TIMEZONE: 'EST' # GMT, UTC-3, etc
  
# MOTD Config | Placeholders: %newline%, %time%
MOTD: '&c&lPotHQ &7| &4&l75% OFF &f@ &4&lstore.pothq.com &c❤ %newline% &7» &a&lHCF SOTW &ftakes place in &c&l&n%time'

# End Config
END:
  TEXT: '&c&l&nRIGHT NOW!!'
  COMMAND: '' # whitelist off

# Text Config
DAYS: 'd' #d #day etc.
HOURS: 'h' #h #hour #hrs etc.
MINUTES: 'm' #m #minute #mins etc.
SECONDS: 's' #s #seconds #secs etc.

# Misc Config
SLOTS: 3500 # Max Slots
CLOCK-TYPE: 1 # 1 (custom) or 2 (d:h:m:s)
